language: node_js

node_js:
  - 0.10.25

rvm:
  - 1.9.3

jdk:
  - openjdk7

env:
  global:
  - secure: Ae20K6NT9dfFCqp66KHklLbx+OLYDTuIuERb6WijIHrgtQNHsxpBIKrAV8fpFviM9+EC21ESlGBd2mYX2Hjf49ijBqw4tLp4x4OkfUaBFtz7rcKYpJP70udgs1SEJHWUcm3EqVzOgmprcGeHbsEJ5m3ZTJDntP4FDwn6Y3AP4SA=
  - secure: zruRnG+yjV+gMfZ/hTbZpugAsbrhwJwg/yKPuGfnwdkSQlA+waVw6XjUdFIT2l0XVWTxtffuQtYpu+RiyTI+5wz/vqXaTi1Q6K+PiYGDAxOgV/KUF0NceBhylfi7J0W1S6JxdswcH8e+tbXPjfT0DyR6URuPNgUmvPHiboH5Us4=
  - secure: uk5n6hXIV5f0A8GeOcqgrlbmjeZQ+F0IYDPZ7eyPBt+05tf7lQFsvv0PhVyR4yzCfhsdFmLPWDPxLk4W7PjkikQhujCpyIRIWJEom6mDWKSDtnuuvzvjAxx+pX5TkqbwZBcAjdRL4YTnOkdNF6ymxnn99oyWVyXOK5m0LrAdtho=
  - secure: tSrXcLpXrfx7NxFuSwSQ2PdgSXkKBnWTaDWtlEglAddjtB4MwnxDs36XqQMhnkIg/wXhKNbjmei9auQ8AjenUx6EjokHSEAMg+ws19mgu+LQrHToCC4QolRSBpj4RkxOA7ehdigeqxulEJEQ1fxyLzOmKdyOCyEGSGMPaMvInaw=
  - secure: XpFlJUwNh5F/Ci5oR/10pxIawl2en+o5VK1cRDAeuBskSxb7KoVgThd19gP2ltZfkrY1DSiddFJ6O+PX8Si8jXEzQEJDhZq+gbOOmNzUaI8lYGtCp3za+brVBwSmigdz/RahuSvGdG7QGL8+y4JIoWsA/JQ7QmSHm9zY1Z4GA7M=
  - secure: Byxv+BJP0PHiAd1nI/zP4pC4pKSUg7o/LC26VqfXluncIILCQ60bmQhgydB7eohA8+q0GofnHSU92wtURR5aP/wTSSb0D8p7Ug+FLCnQWKRxmGvJwwK46sdNZCdUiGLlCiknX+91CbxGtMGQrZXqgWumq8qk14bPJnyf/rnsaKs=
  - secure: iw82IEnglwk1NJfb/Kn0dMv5JqIqzcggMlx/0GDkSQ+anuFceMnpNP5lxutLFxMwedIMvXaVduATGkopJ6YtTnCC96GWW9JX5zcztd+3TiWa1euy/Rw1v7I3MuEBzs9lpU+8US4aVlcq35cYmjFRx7kqYra2sgT/2PPv9GMvl0Q=

before_install:
  - gem install foreman -v 0.61

script:
  - foreman start & mvn clean test

deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: V3lqI/IpNGhVSva1gveNPo+cc+wzfuM1OfjQbNTcFpq21BxL5bAoL87mDf6Wa7BoI96Bsje8P/motBJvLbocjlE2H+NJoccRqiKLSuV0eY0F4OtJHMs23wJEGugHc9EZ3Ml7qiHgfevGWk6/n1JPC5VOFsd/pE9Dbh+80+7Ht70=
  app:
    master: edmunds-widgets-development
    staging: edmunds-widgets-staging
    production: edmunds-widgets-production

notifications:
  email: false
