language: node_js

node_js:
  - 0.10.25

rvm:
  - 1.9.3

jdk:
  - openjdk7

env:
  global:
  - secure: a0eCYdxL1ifrYxaQscM/yAv8mKXL0vnSSzeWJEAARVIBMQBVjJ3YpMRuLN29BhKG0IgM4qmn+4syRXusd+R4+qjflXlqVEOC6MwJPYRqSS4qo4uKfHUuwH/ZjLPsWjpstExEMGEWIxg0a2KW5LOAPuBKbrEs9/eHlIO6Yg0Erwg=
  - secure: rh4XSCUgfNrithKwQc52JIicVF5JQlehN1LlKt7ZqR8qhWCr3aIajV1rJYfzqEYQ3wQTM0kD9EbrwC+SQR+Ycm/RzH0+DNbZDkmptnPFHQP7epf3BKjlZmjCOvVkxRcIYpc5pgmEG6zfNqKPvdSb5qVO80rHlr5FWwwNYGoe/FY=
  - secure: cO3nCPlF2MdbPvgYzSRmqY2TZVHZNxcMk3AISe6jYSt8GC8ZyPFJIaaGLJsuQiaTemQqjPhgxF+InR4K6BPGDdgqeAjh0YvQhjC4PpHajrRE2XMGGXaXVNDAOl8oPeswWeduRvmxaeXR07ZPzYW5BxEbeZVcaF9Dtj0CnXvlPNE=
  - secure: Cg/9ggISlEvzUsU3UgZTu2zSg9gEv8U22eXiFbe6SJEYobZ5xxYYabhCeVzhWUBBjQhuTZxrAYJFgLDnahMqZp5h/+x639W1SGAGi0NoYNJCEPoOK1xX6mtJqcyPSIqm6oqYWA9+iAx9txhfM6BnqEhnLKW3O6RUYeyE/XNZIkU=
  - secure: jm8Gf7Kt/WevzngT4Tr3ly38OMPnV81VFECmRABpNgIBZMp/PmVgrbtIMn7WK1BI4ALKlVpBY+qDGNcRVm6P/2txEHW0U/R4HuRgEMGf+LNn02i2TMSg+SYxMKEr9OtbgzEGdsq2/NDUHZM2rsez1rPrgWTi9+k2gywRq7xVdvo=
  - secure: CO0tRBCsFegtGLHdEma9D2xWHyTRuX6kKrNOJVYVMwdvGtYPMbtG9ynFfOrFX3amn90wsgWGJF0vvCN8wz0qZtmQebeUipfuL/peHGWvIXiNQuWfiXIqEi5WCRzL6jdwmxjqH+WbanKEdDfkwnZFX2ZMKZTV57UKEAB3M1b4wGA=
  - secure: iKF+PNnNDVYfMzD+nnp3ugUG2/qdtp3tGW79fAqDBKZcHCvJGssCUhifGjyR2Og3YgNKqb+bl2k7gUrRfhBa3HHDteXsk28vKDWc8QNvrYkMX1uuwXulErFQ+1H7TWFcrUZcRHQQ4DRZGaq9Dphe9kYHdXaccUgrjN2z1aurDpk=

before_install:
  - gem install foreman -v 0.61

deploy:
  provider: heroku
  strategy: git
  api_key: b2517405-051a-4790-bfa5-c114e5b8435c
  app:
    master: edmunds-widgets-development
    staging: edmunds-widgets-staging
    production: edmunds-widgets-production

notifications:
  email: false
