language: node_js

node_js:
  - 0.10.25

rvm:
  - 1.9.3

jdk:
  - openjdk7

env:
  global:
  - secure: GwGFxPwcl6dbrutwTUvXRLDZYBXbFh2OyPAlupSc5r8uNjvMoGe9S0Pr3PIdpO72J1Q3vTuckkTAxNSNH9RZYXdyEj1tEGjLArMBGOBBHVjmBPCfxhTlBVLJ/ZX9YPD3TkqYd5uvwQzZIMb5PCR2QIQcXMMM12zr3fRpx/aFnIg=
  - secure: YcyHCk93awGWVWXOajLPfCaI2rdL5ELR//ctaMKHtr0dvFm2FHVkt1PmY8mu5m4nNxAucgYW2J7BNBUU+XTVdxF3lO2ZSCIrs8XB4U5ZcsCoQmxNtVDH/GkWRw6+JibbWskSktD+Mt/jRTcnuPSjiehPa+7Gmta+BYSuFAafuM4=
  - secure: pnKrAOWF5Yz4FqdAabAQTkeGhuJMQJWradTpH7lqdta4Rpn8IpNLwoG/4P0NXfpjpAluXNHH1e+P9Lk6KNRcaAwcEWh7IC6724KlY7vQdz7NUHkF19v9Mx9FgW32a+MW5SMf9R42EgIpDubDp+oY7HCrxAoX+nmQ9GL2+e7S5cE=
  - secure: v6y+75yb+jnVNRRetnPdM4Dgya6Uu5xA3TrZ3netjMe+o7PxzWUmL8mTk1PW62+X/zBzU3Jl5GYRqQDoFuKAbiQR6GgzUWiQTz+h5Vw4rHW3VAJcRxr05BhWtzwUgV9B8lUK9ZFinEeY6hXU4Q/eyvcAm4cgc7bAmGoJxUyDBRE=
  - secure: sgCZt/nSjD2zUo5aKgfEIg37/v+NhkpkDBfZzNpOgECGcqNxnQ292LjEi9aJK8VATtwSZfbe6FThNO3P2lVsJlpr4d/0NqdAh8EZHGQmiN8dDrv3Mj5QZfi3xemPFfrEZEvzyVwbOhcd9DO49arFuOGLmc4uZAXG9sLQJ8EZmbA=
  - secure: x2vchdJHSJpqJKBvXUrWTHvzOLxa+2qUwnnXN/cS9Ct6Tema/V0Asw5awTi7gqpGr9aYb/96pfEFFpsWvnVf4pyABP/1gxLWkhLoYQIwfqgLYrXfvcmFNqGa9Hez1m40QqyjGb7EwDVgzvtuteI4KY1f87R2tZku6D4hHIZ/vWk=
  - secure: dFlnNv6m2eMimf3lSWyIJY+FeooP74d22v50htABN8M2oH3h/cR2zvGgUu/wvtXh92YHawWCL2HlX2fF8e7tsA2IIFzs7OWrDMolCtS0PXn6v/Hx7WCl0NDQ0/ZK2AeZD+iu0yQkjbDrHjxhQ+h/hbnsKjsWaMNWdpF6eWG2Pmo=

before_install:
  - gem install foreman -v 0.61

deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: CR2OVvlsM3Wb6z46BD+WkdzL9p/eTc5UO5MLMXHDqUhg988J/YEfg3sqadFboqesmNliobY5AK1fe/00PUN6H5HFZ7tBwoLpfElhC3g+aQ9JbLX1y+A/QlvRN69g1mvce1o6Aw+270qYJEm2js+FaSa4hBPuEEAd+a0bkC2xZjc=
  app:
    master: edmunds-widgets-development
    staging: edmunds-widgets-staging
    production: edmunds-widgets-production

notifications:
  email: false
