language: node_js
node_js:
- 0.10.26
rvm:
- 1.9.3
jdk:
- openjdk7
env:
  global:
  - secure: RalJW7jLXnHTqe0ZpDfzxNtXJRQLHfB0Zw77TE/tMO4fVQXcT2HD/T1Vxvwb6YUnstKtBVst278I+wUKqJ50tTYtD+LHN2F4F+dHKAI51wvLeeA4W7Ulssnxyjf/e3tFFQiX35isjo5qsACL++X3cGxRcMIZZGvhbzWNZqTkCvc=
  - secure: KMh2AYwsmlwsC53WEde46QD6qQGhATStbTXja9mH9vKg0DwV/AChUBUzEdqYRsH42isxBw62ni1/Xd6ErjA6Up7PgVg0kw7zV3VWMTRQpSad3JqtQfN8PvPh2ifilpWeLrviB25s8mCaVuJwkZ7gMKIISWvz2Urba7QUiHRfSkY=
  - secure: LCTFmv8wro47sAdj9Di5qbo+OQEgahK8IiRMtolZQ0o4NcBUtXm5WfaeT7vpyUamzu5aHow5yqYnJ3ympGFIrgmIeiwvwi92mkWY8/jzkURAxms4+u+/AINLymTxgq/s/VQRLua24Kg0LGQ7/QNGraNPV5v0JTP071K3yIo0Luc=
  - secure: ft801MFGGdorD3y4LKTdwbo3bJgDIB+/jPBcuov3A4w0pe3pWXYwVSGVMSFAnSi9OK0Uw9+OHTiCPn6b0HifmLEHtsmCU+pug9DfdyLetpDwoPjBJEqgr6aOPSUHrDizMhUwpDieyBKm23wlEkgyYOzfqW4extz2onEZd+81csk=
  - secure: e7luh2Gk0olzClM1RGjoQ8hqvkqZ3U+XH15UrWHXxY4VT36SlUXQ4fabcO0nltv1tFgSWbJaworvDXkN6PuQK2yas+HABTuA9ckaR4lGOae3eaK+UUxwH4LXyTBaNK+Kq6LKKNXecJmWj7P4bZ+BQU/YS/DQaLqrxQIiImTObc0=
  - secure: WtU5U9M4ZkSeRjIchGYZ/oGO6uTUQ5BE8zEW7rCemNNMnVkQvHId6swFvV4yMkwyYkTN9QuKz42OB6d+FPUfO4dDsXrTmsKJwrlinm1VHFTZ2DiMrzoQnoRsqqi1nNF4Vh+UGSiwRszjI8iKebhBauDHHcQRfEIapJdRR57t9t8=
  - secure: JI8uSNEzQ9rpfiRP9XqqhDLGiuVWNi4GNSlHmVE/pa3bqD6MAxAnJsRAfyNPB6sxxzxUcDx/FzCVjDCqj1UB+1nsyvnTkARlWwz+6xhcu8RtYQFkwVabYaLwP4ORQmTh+XImCOKK+FQKDraUrhcPqqowEUOP8wi19UE9U5tKkNs=
before_install:
- gem install foreman -v 0.61
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: gJsZb3pKIf4qwFXmniUzU2Jp7fhKZcNafPkt5W4etwqRgEeMj8VWyVIMHpW2Z3uxjSMdc+L0cw8GEG8vfSxuvJt3XfpaIEyYlZZpODGzWL84tItf65zsGxxQ7gHLh0w+3fCAZufEFAEBOccW2kA4uT2N4MxcokXXpud1o+WUrR0=
  app:
    master: edmunds-widgets-development
    staging: edmunds-widgets-staging
    production: edmunds-widgets-production
notifications:
  email: false
