language: node_js
node_js:
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: IER0AhtZBkmwqWUI5/tpfv7du77yqnL8v0IdeaidQHZ7ucRPG8GBxY/+gpec17TTet6lsrK3dU7Hk4QXWKQSL2gu59zgY89x+o1LDSbY9otjqDJhJ7ipvm6WkctGJRYNphki40VgrfPbTFs3joW6dOff/jtFzR93ppsIp6E2eLE=
  app:
    master: edmunds-widgets-dev
    staging: edmunds-widgets-staging
    production: edmunds-widgets-prod
  run:
    secure: O5O5tChTo524JLy2hHr4yPXYviPCnGE66iShCqjkf8rJzAiZzoU2dFW7ZyhwPJe30sAEHD9xiqtoCFlhwYGeB28XhE2c/KQ++frp9kfkfxjbwonIxDVVflUswAnbKlTvGyNs+nuPrvK6LbpTqnmDf0+9JHp1TS0t4Dc0FNdTvXk=
notifications:
  email: false
