language: node_js

node_js:
  - 0.10.25

rvm:
  - 1.9.3

jdk:
  - openjdk7

env:
  global:
  - secure: Ku6d/MOB1BLekfVj6s0oTnfFamoUxf3BXY1II5+V+d8diDpEL3VL0v5TM+yicIhYuM9VGhgpkMj56RT0u+LAh1c3Dw9Sb5Wk2lT+LhJw051//guNGlI7o376rsHOyVVpx7W5eHuR1TzkiN4N/fYaI1K7s9Co3D96eCZde16ixy0=
  - secure: Cq/u6TGvCL/LN2G1UikdIP77NV7iwKrQYeFWNR+LygH+BEECXh0+FJ/QgrvrGiSXhkEdErtLY/AV0s2ZTs3QFkKaHyCr+BdJwwz/XWiktVpR+6kP7iQA40hg/El93vCXgy30up8E8ENWmgLU4z/Ybcr07W09nPK3MbkkJWROmkU=
  - secure: ML2v82daBaN1WY9U3+F6RoVvAsaKhrpw/FzUUIzCkdggCP88B1lR1Yvgkw2by6ymg7eX5j7whXPQURssCQkBhp6Wc50RWrgjdDirqjccBLZYLffKkmi2SHWzoZNVjmL34ixm7idHPVA1TEGy/GM+WB9ghT9IRIhkg+jlxgJZEro=
  - secure: k7fnnwblXOThDffXsBUw/qcMX7oA6eSfCATSKOWzbZwJafuqFxc0zXliTPfMbbO2H9Iqxv2Aut/rV2p4hCYLFSr/UiwbVoBj5J5PCgywYm9U6B/w2UXfhi5IWJm3IzMiyqLwF+hgVh6GwU9Rnp+LhLuukS8DbNVtKF29kN4XJ04=
  - secure: f3Ej17YXr9n35XIn+rcPd2F0s24cOs3/sIA5PsZdkdoqAkhM0Ag7bUo3l08NNwEmsrCE5UlXLIs395IgkhVJ1EgQaIllz6wHHzBEhylzNTODjlkepdiJ7xeIRRjFJVJAd+ge6GWYRIF2iqVgis6UuCA86J0F0iRF/xWZSgqNf+U=
  - secure: SshhLc81MGBZqTigxJP2MFz351gzTaqRiovLXXnFNAATqAoGXbGfRqKY27BIVRnBEd/Uijxh8LiVMj0msvDnetMcOyFybWDGT25GGsOkXk7AknPp2srfPfmMLhIO2/UgzljzYIzek16b3sgvSrKFmtI2ANrwb7Ju85cMwz846mw=
  - secure: N8epfZ/R7rUYfJXhCecr/31y2GOG8as9WPWb35OJB6+Mf9/SZ4hm9236uMq8p9iFpVnUZm2R/K3QSf3vGypj/J08EJW7+WOrcNDjbqGoACaIU+Z+fgDjs8OnrJBTF4sd4mXsHHZRsmZ8ABNCI7XCJDybaY3ws6lqQ4UDCy+LVUU=

before_install:
  - gem install foreman -v 0.61

deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: eIlqml9caqkvptFBwkY4OaOdkqAjettdTJxby0qkBlPhdRcaERa/4M7B52dEJAfYN3N1HyoJffFzcQbsOsKzSTYC/+tyaSms+zCVfoQqiUdIt8figjudv9ws7479eHfj1h4tZffQYuiNm/gZDd3OCbuqPXWo+1a1ytxWa0J3Bpw=
  app:
    master: edmunds-widgets-development
    staging: edmunds-widgets-staging
    production: edmunds-widgets-production

notifications:
  email: false
