var env = process.env;

module.exports = {
    // mashery settings
    MASHERY_SITE_ID:                    env.MASHERY_SITE_ID,
    MASHERY_API_KEY:                    env.MASHERY_API_KEY,
    MASHERY_SHARED_SECRET:              env.MASHERY_SHARED_SECRET,
    MASHERY_VEHICLE_SERVICE_KEY:        env.MASHERY_VEHICLE_SERVICE_KEY,
    MASHERY_DEALER_SERVICE_KEY:         env.MASHERY_DEALER_SERVICE_KEY,
    MASHERY_DEALER_OAUTH_API_KEY:       env.MASHERY_DEALER_OAUTH_API_KEY,
    MASHERY_DEALER_OAUTH_SHARED_SECRET: env.MASHERY_DEALER_OAUTH_SHARED_SECRET,
    // widgets
    TMV_LATEST_VERSION: '0.2.1',
    NVC_LATEST_VERSION: '0.2.0'
};
