var env = process.env;

exports.MASHERY_SITE_ID                     = env.MASHERY_SITE_ID;
exports.MASHERY_API_KEY                     = env.MASHERY_API_KEY;
exports.MASHERY_SHARED_SECRET               = env.MASHERY_SHARED_SECRET;
exports.MASHERY_VEHICLE_SERVICE_KEY         = env.MASHERY_VEHICLE_SERVICE_KEY;
exports.MASHERY_DEALER_SERVICE_KEY          = env.MASHERY_DEALER_SERVICE_KEY;
exports.MASHERY_DEALER_OAUTH_API_KEY        = env.MASHERY_DEALER_OAUTH_API_KEY;
exports.MASHERY_DEALER_OAUTH_SHARED_SECRET  = env.MASHERY_DEALER_OAUTH_SHARED_SECRET;

exports.TMV_LATEST_VERSION = '0.2.1';
